server:
  port: 7003

spring:

  ### JPA Config
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  ### Database Connection
  datasource:
    url: jdbc:mysql://localhost:23306/default
    username: default
    password: 1234
